USE my_catering_db;
SET NAMES utf8mb4;

INSERT IGNORE INTO menu_items (name, category, price) VALUES
-- Sambar, Kuzhambu & Rasam
('Prawn Thokku', 'Sambar, Kuzhambu & Rasam', 120.00),
('Mutton Kuzhambu', 'Sambar, Kuzhambu & Rasam', 100.00),
('Mutton Kurma', 'Sambar, Kuzhambu & Rasam', 110.00),
('Fish Curry', 'Sambar, Kuzhambu & Rasam', 90.00),
('Egg Curry', 'Sambar, Kuzhambu & Rasam', 30.00),
('Crab Rasam', 'Sambar, Kuzhambu & Rasam', 80.00),
('Chicken Kuzhmbu', 'Sambar, Kuzhambu & Rasam', 30.00),
('Chettinad Chicken Kuzhambu', 'Sambar, Kuzhambu & Rasam', 30.00),
('Curd', 'Sambar, Kuzhambu & Rasam', 30.00),
('Butter Milk', 'Sambar, Kuzhambu & Rasam', 30.00),
('Tomato Rasam', 'Sambar, Kuzhambu & Rasam', 30.00),
('Udupi Rasam', 'Sambar, Kuzhambu & Rasam', 30.00),
('Pineapple Rasam', 'Sambar, Kuzhambu & Rasam', 30.00),
('Pepper Rasam', 'Sambar, Kuzhambu & Rasam', 30.00),
('More Kuzhambu', 'Sambar, Kuzhambu & Rasam', 30.00),
('Kara Kuzhambu', 'Sambar, Kuzhambu & Rasam', 30.00),
('Manathakali Vathakozhambu', 'Sambar, Kuzhambu & Rasam', 30.00),
('Vattal Kuzhambu', 'Sambar, Kuzhambu & Rasam', 30.00),
('Drumstick Small Onion Sambar', 'Sambar, Kuzhambu & Rasam', 30.00),
('Arachu Vitta Sambar', 'Sambar, Kuzhambu & Rasam', 30.00),
('Mixed Veg Sambar', 'Sambar, Kuzhambu & Rasam', 30.00),
('Kadhambam Sambar', 'Sambar, Kuzhambu & Rasam', 30.00),
('Sambar', 'Sambar, Kuzhambu & Rasam', 30.00),
-- Rice Items
('Prawn Biryani', 'Rice Items', 180.00),
('Mutton Biryani', 'Rice Items', 200.00),
('Fish Biryani', 'Rice Items', 160.00),
('Chicken Biryani', 'Rice Items', 150.00),
('Chicken Fried Rice', 'Rice Items', 80.00),
('Jeera Rice', 'Rice Items', 80.00),
('Kashmiri Pulao', 'Rice Items', 80.00),
('Gobi Pulao', 'Rice Items', 80.00),
('Baby Corn Pulao', 'Rice Items', 80.00),
('Mushroom Pulao', 'Rice Items', 80.00),
('Paneer Pulao', 'Rice Items', 80.00),
('Veg Pulao', 'Rice Items', 80.00),
('Palakai Briyani', 'Rice Items', 80.00),
('Mix Veg Paneer Briyani', 'Rice Items', 80.00),
('Mushroom Dum Briyani', 'Rice Items', 80.00),
('Bread Briyani', 'Rice Items', 80.00),
('Mushroom Briyani', 'Rice Items', 80.00),
('Veg Briyani', 'Rice Items', 80.00),
('Mixed Veg Fried Rice', 'Rice Items', 80.00),
('Gobi Fried Rice', 'Rice Items', 80.00),
('Paneer Fried Rice', 'Rice Items', 80.00),
('Veg Fried Rice', 'Rice Items', 80.00),
('Birinji', 'Rice Items', 80.00),
('Lemon Rice', 'Rice Items', 80.00),
('Coconut Rice', 'Rice Items', 80.00),
('Puli Sadham', 'Rice Items', 80.00),
('Curd Rice With Fruits', 'Rice Items', 80.00),
('Curd Rice', 'Rice Items', 80.00),
('Vathakuzhambu Rice', 'Rice Items', 80.00),
('Rasam Rice', 'Rice Items', 80.00),
('Bisibelabath', 'Rice Items', 80.00),
('Sambar Rice', 'Rice Items', 80.00),
('White Rice', 'Rice Items', 80.00),
-- Noodles Items
('Egg Noodles', 'Noodles Items', 70.00),
('Chicken Noodles', 'Noodles Items', 70.00),
('Hakka Noodles', 'Noodles Items', 70.00),
('Mushroom Noodles', 'Noodles Items', 70.00),
('Mix Veg Noodles', 'Noodles Items', 70.00),
('Gobi Noodles', 'Noodles Items', 70.00),
('Paneer Noodles', 'Noodles Items', 70.00),
('Veg Noodles', 'Noodles Items', 70.00),
-- Side Dish - Gravy
('Vanjaram Fish Fry', 'Side Dish - Gravy', 140.00),
('Tandoori Chicken Tikka', 'Side Dish - Gravy', 120.00),
('Pepper Chicken', 'Side Dish - Gravy', 60.00),
('Mutton Sukka', 'Side Dish - Gravy', 130.00),
('Mutton Paya', 'Side Dish - Gravy', 120.00),
('Mutton Keema', 'Side Dish - Gravy', 100.00),
('Mutton Curry', 'Side Dish - Gravy', 60.00),
('Crab Curry', 'Side Dish - Gravy', 150.00),
('Chicken Chettinad', 'Side Dish - Gravy', 100.00),
('Chettinad Pepper Chicken', 'Side Dish - Gravy', 60.00),
('Butter Chicken', 'Side Dish - Gravy', 110.00),
('Andhra Pepper Chicken', 'Side Dish - Gravy', 60.00),
('Vegetable Kurma', 'Side Dish - Gravy', 60.00),
('Veg Stew', 'Side Dish - Gravy', 60.00),
('Veg Paya', 'Side Dish - Gravy', 60.00),
('Veg Kofta Curry', 'Side Dish - Gravy', 60.00),
('Poori Masala', 'Side Dish - Gravy', 60.00),
('Paneer Butter Masala', 'Side Dish - Gravy', 60.00),
('Mushroom Gravy', 'Side Dish - Gravy', 60.00),
('Mix Veg Curry', 'Side Dish - Gravy', 60.00),
('Malai Kofta', 'Side Dish - Gravy', 60.00),
('Dal Makhani', 'Side Dish - Gravy', 60.00),
('Chenna Masala', 'Side Dish - Gravy', 60.00),
('Cashew Gravy', 'Side Dish - Gravy', 60.00),
('Brinjal Gravy', 'Side Dish - Gravy', 60.00),
('Aloo Gobi Masala', 'Side Dish - Gravy', 60.00),
-- Starters
('Mutton Kola Urundai', 'Starters', 90.00),
('Keema Samosa', 'Starters', 80.00),
('Grilled Chicken', 'Starters', 80.00),
('Fish Manchurian', 'Starters', 90.00),
('Fish Fingers', 'Starters', 80.00),
('Fish Cutlets', 'Starters', 80.00),
('Crab Lollipop', 'Starters', 130.00),
('Chicken Popcorn', 'Starters', 80.00),
('Chicken Pakora', 'Starters', 80.00),
('Chicken Lollipop', 'Starters', 100.00),
('Chicken Chukka Varuval', 'Starters', 80.00),
('Chicken Chintamani', 'Starters', 80.00),
('Chicken 65 Leg Piece', 'Starters', 100.00),
('Chicken 65', 'Starters', 80.00),
('Boiled Egg', 'Starters', 80.00),
('Veg Spring Roll', 'Starters', 80.00),
('Veg Seekh Kebab', 'Starters', 80.00),
('Veg Sandwich', 'Starters', 80.00),
('Veg Roll', 'Starters', 80.00),
('Veg Puff', 'Starters', 80.00),
('Veg Nuggets', 'Starters', 80.00),
('Veg Manchurian', 'Starters', 80.00),
('Veg Lollipop', 'Starters', 80.00),
('Veg Cutlet', 'Starters', 80.00),
('Samosa', 'Starters', 80.00),
('Paneer Tikka', 'Starters', 80.00),
('Paneer Spring Roll', 'Starters', 80.00),
('Paneer 65', 'Starters', 80.00),
('Mushroom Spring Roll', 'Starters', 80.00),
('Mushroom 65', 'Starters', 80.00),
('Honey Chilli Paneer', 'Starters', 80.00),
('Honey Chilli Gobi', 'Starters', 80.00),
('Hara Bhara Kebab', 'Starters', 80.00),
('Gobi Manchurian', 'Starters', 80.00),
('Gobi 65', 'Starters', 80.00),
('Chilli Paneer', 'Starters', 80.00),
('Baby Corn Manchurian', 'Starters', 80.00),
('Baby Corn 65', 'Starters', 80.00),
('Aloo Tikki', 'Starters', 80.00),
-- Soup
('Mutton Leg Soup', 'Soup', 60.00),
('Mutton Bone Soup', 'Soup', 60.00),
('Crab Soup', 'Soup', 70.00),
('Chicken Soup', 'Soup', 40.00),
('Chicken Clear Soup', 'Soup', 40.00),
('Pumpkin Soup', 'Soup', 40.00),
('Spinach Soup', 'Soup', 40.00),
('Carrot Ginger Soup', 'Soup', 40.00),
('Drumstick Soup', 'Soup', 40.00),
('Mushroom Soup', 'Soup', 40.00),
('Cream of Tomato Soup', 'Soup', 40.00),
('Veg Clear Soup', 'Soup', 40.00),
('Creamy Mushroom Soup', 'Soup', 40.00),
('Tomato Soup', 'Soup', 40.00),
('Hot & Sour Soup', 'Soup', 40.00),
('Sweet Corn Soup', 'Soup', 40.00),
('Vegetable Soup', 'Soup', 40.00),
-- Snacks
('Vazhakai Chips', 'Snacks', 25.00),
('Vazhaipoo Vadai', 'Snacks', 25.00),
('Vattal', 'Snacks', 25.00),
('Thayir Vadai', 'Snacks', 25.00),
('Tandoori Papad', 'Snacks', 25.00),
('Sambar Vadai', 'Snacks', 25.00),
('Round Appalam', 'Snacks', 25.00),
('Potato Chips', 'Snacks', 25.00),
('Paruppu Vadai', 'Snacks', 25.00),
('Onion Vadai', 'Snacks', 25.00),
('Onion Pakoda', 'Snacks', 25.00),
('Nenthiram Chips', 'Snacks', 25.00),
('Neetu Appalam', 'Snacks', 25.00),
('Mysore Bonda', 'Snacks', 25.00),
('More Melagai', 'Snacks', 25.00),
('Mini Samosa', 'Snacks', 25.00),
('Medu Vadai', 'Snacks', 25.00),
('Masal Vadai', 'Snacks', 25.00),
('Masal Bonda', 'Snacks', 25.00),
('Kuzhi Paniyaram', 'Snacks', 25.00),
('Kaara Paniyaram', 'Snacks', 25.00),
('Cashew Pakoda', 'Snacks', 25.00),
('Bajji', 'Snacks', 25.00),
('Appalam', 'Snacks', 25.00),
-- Tiffin
('Idiyappam', 'Tiffin', 35.00),
('Semiya Kichadi', 'Tiffin', 35.00),
('Rava Kichadi', 'Tiffin', 35.00),
('Rava Bath', 'Tiffin', 35.00),
('Semiya Bath', 'Tiffin', 35.00),
('Lemon Sevai', 'Tiffin', 35.00),
('Coconut Sweet Sevai', 'Tiffin', 35.00),
('Coconut Sevai', 'Tiffin', 35.00),
('Ghee Pongal', 'Tiffin', 45.00),
('Pongal', 'Tiffin', 35.00),
('Aappam', 'Tiffin', 35.00),
('Adai', 'Tiffin', 35.00),
('Onion Uttappam', 'Tiffin', 35.00),
('Mini Uthapam', 'Tiffin', 35.00),
('Rava Dosa', 'Tiffin', 35.00),
('Podi Dosa', 'Tiffin', 35.00),
('Pesarattu Dosa', 'Tiffin', 35.00),
('Masala Dosa', 'Tiffin', 50.00),
('Ghee Roast Dosa', 'Tiffin', 60.00),
('Chettinad Dosa', 'Tiffin', 35.00),
('Dosa', 'Tiffin', 35.00),
('Thattu Podi Idly', 'Tiffin', 35.00),
('Thattu Idly', 'Tiffin', 35.00),
('Thattu Ghee Podi Idly', 'Tiffin', 35.00),
('Sambar Idly', 'Tiffin', 35.00),
('Podi Idly', 'Tiffin', 35.00),
('Mini Podi Idly', 'Tiffin', 35.00),
('Mini Idly', 'Tiffin', 35.00),
('Mini Ghee Idly', 'Tiffin', 35.00),
('Kushboo Idly', 'Tiffin', 35.00),
('Kancheepuram Idly', 'Tiffin', 35.00),
('Heartine Idly', 'Tiffin', 35.00),
('Gulfi Idly', 'Tiffin', 35.00),
('Garlic Podi Idly Fry', 'Tiffin', 35.00),
('Chilli Idly', 'Tiffin', 35.00),
('Idly', 'Tiffin', 35.00),
-- Tiffin Side Dish
('Coconut Milk', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Idli Podi', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Kumbakonam Kadapa', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Vada Curry', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Verkadalai Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Pudhina Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Coriander Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Tomato Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Onion Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Kaara Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Coconut Chutney', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
('Tiffin Sambar', 'Tiffin Side Dish - Sambar, Chutney & Others', 20.00),
-- Indian Breads
('Aloo Paratha', 'Indian Breads', 20.00),
('Chilli Parotta', 'Indian Breads', 20.00),
('Coin Parotta', 'Indian Breads', 20.00),
('Bun Parotta', 'Indian Breads', 20.00),
('Parotta', 'Indian Breads', 15.00),
('Chola Poori', 'Indian Breads', 20.00),
('Poori', 'Indian Breads', 20.00),
('Chapathi', 'Indian Breads', 20.00),
('Garlic Naan', 'Indian Breads', 30.00),
('Butter Naan', 'Indian Breads', 30.00),
('Naan', 'Indian Breads', 20.00),
('Phulka', 'Indian Breads', 20.00),
('Tandoori Roti', 'Indian Breads', 20.00),
('Rumali Roti', 'Indian Breads', 20.00),
('Roti', 'Indian Breads', 20.00),
-- Side Dish - Poriyal, Kootu & Aviyal
('Veg Prawn Fry', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Veg Liver Fry', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Veg Fish Fry', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Vazhakkai Varuval', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Stuffed Kathirikai', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Senai Varuval', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Senai Chops', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Pudalai Kootu', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Potato Kaara Kari', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Potato Green Peas Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Potato Finger Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('National Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Malabar Aviyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Kose Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Kerala Avial', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Kathirikai Chops', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Kadhambam Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Chow Chow Kootu', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Cheppakizhangu Fry', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Carrot Beans Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Cabbage Kootu', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Beetroot Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Beans Paruppu Usili', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Aviyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
('Avarai Poriyal', 'Side Dish - Poriyal, Kootu & Aviyal', 30.00),
-- Raita, Pickle & Other
('Banana', 'Raita, Pickle & Other', 20.00),
('Elai Paruppu & Ghee', 'Raita, Pickle & Other', 20.00),
('Ghee', 'Raita, Pickle & Other', 20.00),
('Parupu Podi with Nallennai', 'Raita, Pickle & Other', 20.00),
('Paruppu Podi with Ghee', 'Raita, Pickle & Other', 20.00),
('Mango Thokku', 'Raita, Pickle & Other', 20.00),
('Lemon Pickle', 'Raita, Pickle & Other', 20.00),
('Mango Pickle', 'Raita, Pickle & Other', 20.00),
('Pickle', 'Raita, Pickle & Other', 20.00),
('Sweet Pachadi', 'Raita, Pickle & Other', 20.00),
('Thayir Pachadi', 'Raita, Pickle & Other', 20.00),
('Tomato Raita', 'Raita, Pickle & Other', 20.00),
('Mixed Veg Raita', 'Raita, Pickle & Other', 20.00),
('Boondi Raita', 'Raita, Pickle & Other', 20.00),
('Cucumber Raita', 'Raita, Pickle & Other', 20.00),
('Onion Raita', 'Raita, Pickle & Other', 20.00),
-- Payasam
('Semiya Payasam', 'Payasam', 50.00),
('Semiya Paal Payasam', 'Payasam', 50.00),
('Rava Payasam', 'Payasam', 50.00),
('Paruppu Payasam', 'Payasam', 50.00),
('Paruppu Paal Payasam', 'Payasam', 50.00),
('Paal Payasam', 'Payasam', 60.00),
('Paal Kozhukattai', 'Payasam', 50.00),
('Kerala Adai Payasam', 'Payasam', 50.00),
('Javvarisi Payasam', 'Payasam', 50.00),
('Ilaneer Payasam', 'Payasam', 70.00),
('Arisi Payasam', 'Payasam', 50.00),
-- Sweet
('Rasgulla', 'Sweet', 60.00),
('Rasamalai Roll', 'Sweet', 40.00),
('Rasamalai', 'Sweet', 70.00),
('Rabdi', 'Sweet', 40.00),
('Pineapple Kesari', 'Sweet', 40.00),
('Paruppu Poli', 'Sweet', 40.00),
('Paal Gova', 'Sweet', 40.00),
('Mysore Pa', 'Sweet', 40.00),
('Moti Choor Ladoo', 'Sweet', 40.00),
('Mini Laddu', 'Sweet', 40.00),
('Mini Jangiri', 'Sweet', 40.00),
('Milk Sweet', 'Sweet', 40.00),
('Milk Alwa', 'Sweet', 40.00),
('Malpua', 'Sweet', 40.00),
('Malai Sandwich', 'Sweet', 40.00),
('Malai Roll', 'Sweet', 40.00),
('Lychee Basandhi', 'Sweet', 40.00),
('Laddu', 'Sweet', 40.00),
('Kesari', 'Sweet', 40.00),
('Kasi Alwa', 'Sweet', 40.00),
('Kalyana Jangiri', 'Sweet', 40.00),
('Kalakand', 'Sweet', 40.00),
('Kaju Sweet', 'Sweet', 40.00),
('Kaju Roll', 'Sweet', 40.00),
('Kaju Katli', 'Sweet', 80.00),
('Kaala Jamun', 'Sweet', 40.00),
('Jalebi', 'Sweet', 40.00),
('Gulab Jamun', 'Sweet', 50.00),
('Godhuma Alwa', 'Sweet', 40.00),
('Ghevar', 'Sweet', 40.00),
('Ghee Mysore Pa', 'Sweet', 40.00),
('Dry Jamun', 'Sweet', 40.00),
('Dry Fruit Kesari', 'Sweet', 40.00),
('Doodh Peda', 'Sweet', 40.00),
('Coconut Poli', 'Sweet', 40.00),
('Coconut Barfi', 'Sweet', 40.00),
('Carrot Alwa', 'Sweet', 40.00),
('Bread Alwa', 'Sweet', 40.00),
('Beetroot Alwa', 'Sweet', 40.00),
('Basandhi', 'Sweet', 40.00),
('Asoka', 'Sweet', 40.00),
('Alwa', 'Sweet', 40.00),
('Agra Pan', 'Sweet', 40.00),
-- Drink
('Milkshakes', 'Drink', 60.00),
('Welcome Juice - Essence', 'Drink', 30.00),
('Sweet Lime Juice', 'Drink', 30.00),
('Grape Juice', 'Drink', 30.00),
('Pineapple Juice', 'Drink', 30.00),
('Watermelon Juice', 'Drink', 30.00),
('Seasonal Fruit Juice', 'Drink', 30.00),
('Sukku Malli Coffee', 'Drink', 30.00),
('Butter Milk', 'Drink', 30.00),
('Badam Milk', 'Drink', 50.00),
('Rose Milk', 'Drink', 30.00),
('Hot Badam Milk', 'Drink', 50.00),
('Masala Milk', 'Drink', 30.00),
('Milk', 'Drink', 30.00),
('Horlicks', 'Drink', 30.00),
('Boost', 'Drink', 30.00),
('Coffee', 'Drink', 30.00),
('Tea', 'Drink', 30.00),
-- Common Items
('Service Boys', 'Common Items', 500.00),
('Water Bottle', 'Common Items', 20.00),
('Water Cup', 'Common Items', 10.00),
('Paper Roll', 'Common Items', 10.00),
('Paper Tissue', 'Common Items', 10.00),
('Paper Cup', 'Common Items', 10.00),
('Banana Leaf', 'Common Items', 10.00);

SELECT COUNT(*) AS total_menu_items FROM menu_items;