/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingCateringServicesInChennaiRouteImport } from './routes/wedding-catering-services-in-chennai'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EngagementCateringServicesInChennaiRouteImport } from './routes/engagement-catering-services-in-chennai'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CorporateCateringServicesInChennaiRouteImport } from './routes/corporate-catering-services-in-chennai'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutMyChennaiCateringRouteImport } from './routes/about-my-chennai-catering'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WeddingCateringServicesInChennaiRoute =
  WeddingCateringServicesInChennaiRouteImport.update({
    id: '/wedding-catering-services-in-chennai',
    path: '/wedding-catering-services-in-chennai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementCateringServicesInChennaiRoute =
  EngagementCateringServicesInChennaiRouteImport.update({
    id: '/engagement-catering-services-in-chennai',
    path: '/engagement-catering-services-in-chennai',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateCateringServicesInChennaiRoute =
  CorporateCateringServicesInChennaiRouteImport.update({
    id: '/corporate-catering-services-in-chennai',
    path: '/corporate-catering-services-in-chennai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMyChennaiCateringRoute = AboutMyChennaiCateringRouteImport.update({
  id: '/about-my-chennai-catering',
  path: '/about-my-chennai-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-my-chennai-catering': typeof AboutMyChennaiCateringRoute
  '/admin': typeof AdminRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate-catering-services-in-chennai': typeof CorporateCateringServicesInChennaiRoute
  '/crm': typeof CrmRoute
  '/engagement-catering-services-in-chennai': typeof EngagementCateringServicesInChennaiRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/services': typeof ServicesRoute
  '/wedding-catering-services-in-chennai': typeof WeddingCateringServicesInChennaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-my-chennai-catering': typeof AboutMyChennaiCateringRoute
  '/admin': typeof AdminRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate-catering-services-in-chennai': typeof CorporateCateringServicesInChennaiRoute
  '/crm': typeof CrmRoute
  '/engagement-catering-services-in-chennai': typeof EngagementCateringServicesInChennaiRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/services': typeof ServicesRoute
  '/wedding-catering-services-in-chennai': typeof WeddingCateringServicesInChennaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-my-chennai-catering': typeof AboutMyChennaiCateringRoute
  '/admin': typeof AdminRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate-catering-services-in-chennai': typeof CorporateCateringServicesInChennaiRoute
  '/crm': typeof CrmRoute
  '/engagement-catering-services-in-chennai': typeof EngagementCateringServicesInChennaiRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/services': typeof ServicesRoute
  '/wedding-catering-services-in-chennai': typeof WeddingCateringServicesInChennaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-my-chennai-catering'
    | '/admin'
    | '/builder'
    | '/contact'
    | '/corporate-catering-services-in-chennai'
    | '/crm'
    | '/engagement-catering-services-in-chennai'
    | '/gallery'
    | '/menu'
    | '/services'
    | '/wedding-catering-services-in-chennai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-my-chennai-catering'
    | '/admin'
    | '/builder'
    | '/contact'
    | '/corporate-catering-services-in-chennai'
    | '/crm'
    | '/engagement-catering-services-in-chennai'
    | '/gallery'
    | '/menu'
    | '/services'
    | '/wedding-catering-services-in-chennai'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-my-chennai-catering'
    | '/admin'
    | '/builder'
    | '/contact'
    | '/corporate-catering-services-in-chennai'
    | '/crm'
    | '/engagement-catering-services-in-chennai'
    | '/gallery'
    | '/menu'
    | '/services'
    | '/wedding-catering-services-in-chennai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutMyChennaiCateringRoute: typeof AboutMyChennaiCateringRoute
  AdminRoute: typeof AdminRoute
  BuilderRoute: typeof BuilderRoute
  ContactRoute: typeof ContactRoute
  CorporateCateringServicesInChennaiRoute: typeof CorporateCateringServicesInChennaiRoute
  CrmRoute: typeof CrmRoute
  EngagementCateringServicesInChennaiRoute: typeof EngagementCateringServicesInChennaiRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  ServicesRoute: typeof ServicesRoute
  WeddingCateringServicesInChennaiRoute: typeof WeddingCateringServicesInChennaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-catering-services-in-chennai': {
      id: '/wedding-catering-services-in-chennai'
      path: '/wedding-catering-services-in-chennai'
      fullPath: '/wedding-catering-services-in-chennai'
      preLoaderRoute: typeof WeddingCateringServicesInChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement-catering-services-in-chennai': {
      id: '/engagement-catering-services-in-chennai'
      path: '/engagement-catering-services-in-chennai'
      fullPath: '/engagement-catering-services-in-chennai'
      preLoaderRoute: typeof EngagementCateringServicesInChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-catering-services-in-chennai': {
      id: '/corporate-catering-services-in-chennai'
      path: '/corporate-catering-services-in-chennai'
      fullPath: '/corporate-catering-services-in-chennai'
      preLoaderRoute: typeof CorporateCateringServicesInChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-my-chennai-catering': {
      id: '/about-my-chennai-catering'
      path: '/about-my-chennai-catering'
      fullPath: '/about-my-chennai-catering'
      preLoaderRoute: typeof AboutMyChennaiCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutMyChennaiCateringRoute: AboutMyChennaiCateringRoute,
  AdminRoute: AdminRoute,
  BuilderRoute: BuilderRoute,
  ContactRoute: ContactRoute,
  CorporateCateringServicesInChennaiRoute:
    CorporateCateringServicesInChennaiRoute,
  CrmRoute: CrmRoute,
  EngagementCateringServicesInChennaiRoute:
    EngagementCateringServicesInChennaiRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  ServicesRoute: ServicesRoute,
  WeddingCateringServicesInChennaiRoute: WeddingCateringServicesInChennaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
